### ISSUE TITLE
Days-detection not working - myBB 1.6.9

### ISSUE THREAD

**Issue by bositman** [Sama34/OUGC-Necro-Post-Notice#1]
It seems that the plugin isn't working with the latest myBB version.

It does not correctly display the days the last reply was made and it also shows up  in threads which do not meet the criteria set in admin CP.

Running on nginx 1.2.7 and PHP Version 5.3.23, mysqlnd 5.0.8-dev.

 If you need anything else do tell :)

**Comment by Sama34** [comment]
Thank you, but I was unable to find a cause for this so I'm going to close by now.
